##
## EPITECH PROJECT, 2021
## chocolatine - what_time_is_it.yml
## File description:
## jitter jitter
##

name: What time is it
on: [push]
jobs:
  build:
      name: Example
      runs-on: ubuntu-latest
      steps:
        - name: Get current date
          id: dote
          run: |
            echo "::set-output name=date::$(date +'%Y-%m-%d')"
        - name: getting the time
          id: me_time
          run: echo "::set-output name=moo_time::$(date +'%H-%M-%S-%N')"

        - name: Setting environement variables
          id: my_env_env
          run: |
            echo "::set-output name=tag_name::'The_date_is: $(steps.dote.outputs.date)'"
            echo "::set-output name=release_name::'The_Date_Is: $(steps.dote.outputs.date)'"
            echo "::set-output name=current_time::'The_time_is: $(steps.me_time.outputs.moo_time)'"
            echo "::set-output name=current_username::'Mona_the_Octocat'"
            echo "steps.my_env_env.tag_name is '${{ steps.my_env_env.tag_name }}'"
            echo "steps.my_env_env.release_name is '${{ steps.my_env_env.release_name }}'"
            echo "steps.my_env_env.current_time is '${{ steps.my_env_env.current_time }}'"
            echo "steps.my_env_env.current_username is '${{ steps.my_env_env.current_username }}'"

        - name: Output structure my_env_env content
          run: |
            echo "steps.my_env_env.tag_name is '${steps.my_env_env.tag_name}'"
            echo "steps.my_env_env.release_name is '${steps.my_env_env.release_name}'"
            echo "steps.my_env_env.current_time is '${steps.my_env_env.current_time}'"
            echo "steps.my_env_env.current_username is '${steps.my_env_env.current_username}'"

        - name: Test with input
          uses: actions/hello-world-docker-action@master
          with:
            who-to-greet: "${{ steps.my_env_env.current_username }}-${{ steps.dote.outputs.date }}"
