name: chocolatine
on: [push, pull_request]
jobs:
  check-for-unwanted-files:
    runs-on: ubuntu-latest
    steps:
      - name: cloning directory into the machine
        uses: actions/checkout@v2
      # - name: setup python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.8 #install the python needed
      # - name: execute a python script
      #   run: |
      #     python list_directory.py
      - name: Where am i?
        run: "echo $PWD"
      - name: Display help.
        run: "help"
      - name: What is in my directory?
        run: ls | cat -e
      - name: Only run this if file README exists
        run: "(test -f README && echo README exists) || echo README does not exist, skipping step"
      - name: Only run this if file containing pain_au_chocolat exists
        run: "(test -f pain_au_chocolat && echo pain_au_chocolat exists) || echo pain_au_chocolat does not exists"
      - name: Check if \# is in file
        run: 'for FILE in *; do if grep -q ''#'' $FILE;then  echo "Unwanted file detected: $FILE#L1"; fi; done'
      - name: "Unwanted file detected: Dockerfile~#L1"
        # run: "if grep -q 'Hack_' $File; then  echo 'found # in filename'; fi"
