name: chocolatine
on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'
jobs:
  check-for-unwanted-files:
    runs-on: ubuntu-latest
    steps:
      - name: cloning directory into the machine
        uses: actions/checkout@v2
      - name: check_repository_cleanliness
        run: |
          UNWANTED_FILES=0
          for FILE in *
          do
            echo "UNWANTED_FILES = $UNWANTED_FILES"
            if grep -q "*~" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*-;" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "#*" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "#*#" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*#" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*.o" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*.a" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*.exe" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*.so" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*.gcno" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*.gcda" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*.gcov" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "tmp" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*pain_au_chocolat*" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "*pain_au_chocolat" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi

            if grep -q "pain_au_chocolat*" $FILE
            then
              echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
              UNWANTED_FILES=1
            fi
            echo "UNWANTED_FILES= $UNWANTED_FILES"
          done
          if [ $UNWANTED_FILES -eq 1 ]
          then
            echo "::error file=$UNWANTED_FILES, line=1,endLine=0,title=Check if the repository is clean and void of any unwanted files (temp files, binary files, etc.)::Process completed with exit code 1"
            echo "In UNWANTED_FILES"
            # exit 1
          fi


# name: chocolatine
# on: [push, pull_request]
# jobs:
#   check-for-unwanted-files:
#     runs-on: ubuntu-latest
#     steps:
#       - name: cloning directory into the machine
#         uses: actions/checkout@v2
#       - name: Checking '~' files
#         run: 'for FILE in *; do if grep -q "*~" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '-;' files
#         run: 'for FILE in *; do if grep -q "*-;" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '#*' files
#         run: 'for FILE in *; do if grep -q "#*" $FILE;then  echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done'
#       - name: Checking '#*#' files
#         run: 'for FILE in *; do if grep -q "#*#" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '*#' files
#         run: 'for FILE in *; do if grep -q "*#" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '.o' files
#         run: 'for FILE in *; do if grep -q "*.o" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '.a' files
#         run: 'for FILE in *; do if grep -q "*.a" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '.exe' files
#         run: 'for FILE in *; do if grep -q "*.exe" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '.so' files
#         run: 'for FILE in *; do if grep -q "*.so" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '.gcno' files
#         run: 'for FILE in *; do if grep -q "*.gcno" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '.gcda' files
#         run: 'for FILE in *; do if grep -q "*.gcda" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '.gcov' files
#         run: 'for FILE in *; do if grep -q "*.gcov" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking 'tmp' files
#         run: 'for FILE in *; do if grep -q "tmp" $FILE; then echo "Unwanted folder detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '*pain_au_chocolat*' files
#         run: 'for FILE in *; do if grep -q "*pain_au_chocolat*" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '*pain_au_chocolat' files
#         run: 'for FILE in *; do if grep -q "*pain_au_chocolat" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking 'pain_au_chocolat*' files
#         run: 'for FILE in *; do if grep -q "pain_au_chocolat*" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '*pain*' files
#         run: 'for FILE in *; do if grep -q "*pain*" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '*pain' files
#         run: 'for FILE in *; do if grep -q "*pain" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking 'pain*' files
#         run: 'for FILE in *; do if grep -q "pain*" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '*au_chocolat*' files
#         run: 'for FILE in *; do if grep -q "*au_chocolat*" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '*au_chocolat' files
#         run: 'for FILE in *; do if grep -q "*au_chocolat" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking 'au_chocolat*' files
#         run: 'for FILE in *; do if grep -q "au_chocolat*" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '*chocolat*' files
#         run: 'for FILE in *; do if grep -q "*chocolat*" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking '*chocolat' files
#         run: 'for FILE in *; do if grep -q "*chocolat" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
#       - name: Checking 'chocolat*' files
#         run: 'for FILE in *; do if grep -q "chocolat*" $FILE; then echo "Unwanted file detected: $FILE#L1";echo '::set-output name=SELECTED_COLOR::red'; fi; done;'
