name: chocolatine
on: [push, pull_request]
jobs:
  check-for-unwanted-files:
    runs-on: ubuntu-latest
    steps:
      - name: Only run this if file README exists
        run: "(test -f README && echo README exists) || echo README does not exist, skipping step"
      - name: Only run this if file containing pain_au_chocolat exists
        run: "(test -f pain_au_chocolat && echo pain_au_chocolat exists) || echo pain_au_chocolat does not exists"
