##
## EPITECH PROJECT, 2021
## chocolatine - what_time_is_it.yml
## File description:
## jitter jitter
##

name: What time is it
on: [push]
jobs:
  build:
      name: Example
      runs-on: ubuntu-latest
      env:
        TAG_NAME: "The_date_is:"
        RELEASE_NAME: "The_Date_Is:"
        CURRENT_TIME: "The_time_is:"
        CURRENT_USERNAME: 'Mona_the_Octocat'
      steps:
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        # - name: getting the time
        #   id: me_time
        #   run: echo "::set-output name=mo_time::$(date +'%Hh%Mm%Ss%Nns')

        - name: Test with environment variables
          run: echo $TAG_NAME - $RELEASE_NAME
          # TAG_NAME: "$TAG_NAME ${{ steps.date.outputs.date }}"
          # RELEASE_NAME: "$RELEASE_NAME ${{ steps.date.outputs.date }}"
          # CURRENT_TIME: "$CURRENT_TIME ${{steps.me_time.outputs.mo_time}}"
        - name: output environement variables v1
          run: |
            echo "TAG_NAME is '$TAG_NAME'"
            echo " RELEASE_NAME is '$RELEASE_NAME'"
            echo " CURRENT_TIME is '$CURRENT_TIME'"
            echo " CURRENT_USERNAME is '$CURRENT_USERNAME'"
          # run:
          # run:
          # run:
        - name: Test with input
          uses: actions/hello-world-docker-action@master
          with:
            who-to-greet: ${{ CURRENT_USERNAME }}-${{ steps.date.outputs.date }}
        - name: Test time output
          uses: actions/hello-world-docker-action@master
          with:
            who-to-greet: $CURRENT_USERNAME-${{ steps.date.outputs.my_time }}
