##
## EPITECH PROJECT, 2021
## chocolatine - what_time_is_it.yml
## File description:
## jitter jitter
##

name: What time is it
on: [push]
jobs:
  build:
      name: Example
      runs-on: ubuntu-latest
      steps:
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        - name: getting the time
          id: me_time
          run: echo "::set-output name=mo_time::$(date +'%Hh%Mm%Ss%Nns')
        - name: Test with environment variables
          run: echo $TAG_NAME - $RELEASE_NAME
          env:
            TAG_NAME: "The_date_is: ${{ steps.date.outputs.date }}"
            RELEASE_NAME: "The_Date_Is: ${{ steps.date.outputs.date }}"
            CURRENT_TIME: "The_time_is: ${{steps.me_time.outputs.mo_time}}"
            CURRENT_USERNAME: 'Mona_the_Octocat'
        - name: output environement variables v1
          run: echo "TAG_NAME is $TAG_NAME"
          run: echo " RELEASE_NAME is $RELEASE_NAME"
          run: echo " CURRENT_TIME is $CURRENT_TIME"
          run: echo " CURRENT_USERNAME is $CURRENT_USERNAME"
        - name: Test with input
          uses: actions/hello-world-docker-action@master
          with:
            who-to-greet: ${{ CURRENT_USERNAME }}-${{ steps.date.outputs.date }}
          uses: actions/hello-world-docker-action@master
          with:
            who-to-greet: ${{ CURRENT_USERNAME }}-${{ steps.date.outputs.my_time }}
