##
## EPITECH PROJECT, 2021
## chocolatine - what_time_is_it.yml
## File description:
## jitter jitter
##

name: What time is it
on: [push]
jobs:
  build:
      name: Example
      runs-on: ubuntu-latest
      steps:
        - name: Get current date
          id: dote
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        # - name: getting the time
        #   id: me_time
        #   run: echo "::set-output name=mo_time::$(date +'%Hh%Mm%Ss%Nns')

        - name: Test with environment variables
          id: my_env
          env:
            TAG_NAME: "The_date_is: ${{ steps.dote.outputs.date }}"
            RELEASE_NAME: "The_Date_Is: ${{ steps.dote.outputs.date }}"
            CURRENT_TIME: "The_time_is: ${{steps.me_time.outputs.mo_time}}"
            CURRENT_USERNAME: 'Mona_the_Octocat'
          run: echo $TAG_NAME - $RELEASE_NAME
        - name: output environement variables v1
          run: |
            echo "TAG_NAME is '$TAG_NAME'"
            echo " RELEASE_NAME is '${steps.my_env.RELEASE_NAME}'"
            echo " CURRENT_TIME is '${steps.my_env.CURRENT_TIME}'"
            echo " CURRENT_USERNAME is '${steps.my_env.CURRENT_USERNAME}'"
          # run:
          # run:
          # run:
        - name: Test with input
          uses: actions/hello-world-docker-action@master
          with:
            who-to-greet: "${steps.my_env.CURRENT_USERNAME}-${{ steps.dote.outputs.date }}"
        # - name: Test time output
        #   uses: actions/hello-world-docker-action@master
        #   with:
        #     who-to-greet: $CURRENT_USERNAME-${{ steps.date.outputs.my_time }}
